### ISSUE TITLE
Functions dont work

### ISSUE THREAD

**Issue by heshriti** [b-k/apophenia#37]
Hi,

Some functions/macros are not working. I noticed there are no prototype declaration in the apop.h file.
Can you please resolve this.

Thank you.

For example 
apop_matrix_to_data or apop_vector_to_data.

>>>>
 /usr/bin/ld: error: undefined symbol: apop_matrix_to_data

**Comment by b-k** [comment]
These were removed a while ago because it is more efficient to use a one-liner to declare an `apop_data` struct with one element.  Here are macros to hide the somewhat messy syntax:
```
#define Data_from_matrix(m) &(apop_data){.matrix=(m)}
#define Data_from_vector(v) &(apop_data){.vector=(v)}
```
These macros would generate structs on the stack, which auto-destruct on exit from the scope, so make a copy if so desired. For example,
```
gsl_vector *v = gsl_vector_alloc(100);
apop_data *d_local = Data_from_vector(v);
return apop_data_copy(d_local);
```
There are notes the documentation, but a few layers deep into the tree and easy to miss: http://apophenia.info/dataoverview.html#convsec . If there are still references to the old functions in the documentation, or you would like to clarify or rearrange this part, please submit a pull request. Thanks.
